/**
 * UI copy registry — user-facing strings live here, not inline in JSX.
 *
 * One place to keep tone-of-voice consistent, fix wording, or (later)
 * localize. Keyed structurally: `UI_COPY.<surface>.<string>`. Components
 * compose dynamic fragments around these constants; fully dynamic sentences
 * (interpolating live values) stay in the component but should reuse the
 * shared sentence stems from here where one exists.
 */

/** Placeholder glyph for a missing numeric/data value. */
export const NO_DATA = '--'

/** Empty-state explanations for the trade feed, keyed by backend reason code. */
export const TRADE_FEED_EMPTY_LABELS: Record<string, string> = {
  db_degraded: 'DB unavailable — fills will appear when DB reconnects',
  no_orders_executed: 'No orders executed yet — decisions are being evaluated',
  lifecycle_not_persisted: 'Orders placed but lifecycle rows are pending',
  no_executable_intents: 'Pipeline active — no executable intents yet',
  default: 'No fills yet — waiting for executed trades',
}

export const UI_COPY = {
  app: {
    title: 'Trading Control',
    description: 'AI Trading Control Dashboard',
  },
  nav: {
    overview: 'Overview',
    trading: 'Trading',
    agents: 'Agents',
    challengers: 'Challengers',
    learning: 'Learning',
    proposals: 'Proposals',
    cognitive: 'Cognitive',
    system: 'System',
  },
  header: {
    equity: 'Equity',
    pnl: 'P&L',
    buyingPower: 'Buying Power',
    live: 'Live · Paper',
    halted: 'Halted',
    sidebarFooter: 'Phase 2 · Paper Mode',
    timezone: 'ET',
    clockEmpty: '--:--:--',
  },
  killSwitch: {
    label: 'Kill Switch',
    halted: 'Halted',
    confirmHalt: 'Halt all?',
    confirmResume: 'Resume?',
    confirm: 'Confirm',
    cancel: 'Esc',
  },
  aria: {
    openSidebar: 'Open sidebar',
    closeSidebar: 'Close sidebar',
    toggleTheme: 'Toggle theme',
    closeDialog: 'Close dialog',
    dismiss: 'Dismiss',
  },
  actions: {
    approve: 'Approve',
    reject: 'Reject',
    trace: 'trace',
    traceTitle: 'View the full trace (runs, logs, grades) for this event',
    clear: 'Clear',
    applyPromotions: 'Apply promotions',
  },
  notifications: {
    title: 'Notifications',
    clearAria: 'Clear all notifications',
    streamDisconnected: 'Stream disconnected',
    noneInWindow: 'No notifications in the last hour',
    noneYet: 'No notifications yet',
    fallbackTitle: 'Notification',
    fallbackMessage: 'No message',
  },
  loading: {
    default: 'Loading…',
    challengers: 'Loading challengers…',
    cognitive: 'Loading the brain…',
  },
  activityIndicator: {
    live: 'LIVE',
    waiting: 'WAITING',
    offline: 'OFFLINE',
  },
  system: {
    commandCenter: 'Command Center',
    headline: 'Decisions, risk, execution',
    modePaper: 'Paper / memory',
    modeLive: 'Live capable',
    operatorControls: 'Operator controls',
    apiDownPrefix: 'Dashboard API unreachable',
    apiDownSuffix: '. Live data may be stale.',
    kpiNetPnl: 'Net PnL',
    kpiDailyPnl: 'Daily PnL',
    kpiOpenExposure: 'Open Exposure',
    kpiActivePositions: 'Active Positions',
    kpiRegime: 'Current Regime',
    kpiRiskState: 'Risk State',
    unknown: 'Unknown',
    review: 'Review',
    acceptable: 'Acceptable',
    killSwitch: 'Kill Switch',
    engaged: 'Engaged',
    clear: 'Clear',
    tradingEnabled: 'Trading Enabled',
    enabled: 'Enabled',
    disabled: 'Disabled',
    marketOpen: 'Market Open',
    streaming: 'Streaming',
    noTicks: 'No ticks',
    dataHealth: 'Data Health',
    llmHealth: 'LLM Health',
    llmFallback: 'Fallback',
    healthMarketData: 'Market Data',
    healthTicks: 'ticks',
    healthWebSocket: 'WebSocket',
    healthMsgs: 'msgs',
    healthDisconnected: 'Disconnected',
    healthDashboardApi: 'Dashboard API',
    healthUnreachable: 'Unreachable',
    healthLive: 'Live',
    healthBroker: 'Broker',
    healthOrders: 'orders',
    healthDatabase: 'Database',
    healthMemory: 'Memory',
    healthRedis: 'Redis',
    healthEventBus: 'Event bus',
    healthNoStream: 'No stream',
    healthLlm: 'LLM',
    decisionFeed: 'Live Decision Feed',
    windowed: 'Windowed',
    feedAria: 'Reverse chronological decision stream',
    feedEmpty: 'Waiting for decisions, skips, or executions.',
    confidence: 'Confidence:',
    reason: 'Reason:',
    traceExplorer: 'Trace Explorer',
    tracePrefix: 'Trace',
    traceNotAttached: 'not attached',
    expand: 'expand',
    noOrderRouted: 'No order routed.',
    awaitingGrade: 'Awaiting grade/outcome attribution.',
    activePositionsOf: 'active positions /',
    exposure: 'exposure',
    eventAt: 'event at',
    noTraceSelected: 'No decision trace selected yet.',
    cognitiveEvolution: 'Cognitive Evolution',
    strategyVersion: 'Current Strategy Version',
    lastApproved: 'Last Approved Proposal',
    noneApproved: 'None approved',
    proposalSuccessRate: 'Proposal Success Rate',
    configTimeline: 'Config Change Timeline',
    afterReview: 'after challenger review',
    noMutations: 'No strategy mutations recorded.',
    agentActivity: 'Agent Activity',
    currentTask: 'Current task',
    lastOutput: 'Last output',
    lastSeen: 'Last seen',
    idle: 'Idle',
    noOutput: 'No output yet',
    systemHealth: 'System Health',
    traceColumns: {
      signal: 'Signal',
      reasoning: 'Reasoning',
      risk: 'Risk Evaluation',
      sizing: 'Position Sizing',
      execution: 'Execution',
      outcome: 'Outcome',
    },
  },
  status: {
    connected: 'Connected',
    disconnected: 'Disconnected',
    live: 'Live',
    idle: 'Idle',
  },
  terminal: {
    open: 'O',
    high: 'H',
    low: 'L',
    bid: 'BID',
    ask: 'ASK',
    spread: 'SPR',
    defaultAction: 'hold',
    chartWaiting: 'Waiting for live price data… (feed warming up or market closed)',
  },
  pages: {
    statusLabel: 'System Status:',
    overview: {
      eyebrow: 'Trading terminal',
      title: 'Live equities trading desk',
      description: 'Watchlist, chart, order book, ticket, and blotter in one dense terminal.',
    },
    trading: {
      eyebrow: 'Execution',
      title: 'Trades, fills, and traceable execution',
      description:
        'Monitor open risk, fills, grades, and execution provenance without decorative cards.',
    },
    agents: {
      eyebrow: 'Runtime agents',
      title: 'Agent health and production activity',
      description:
        'Inspect agent heartbeats, streams, decisions, and diagnostics in a dense operations layout.',
    },
    challengers: {
      eyebrow: 'Challenger shadows',
      title: 'Rival strategies on live data',
      description:
        'Follow each shadow challenger: its record, the baseline comparison, and exactly what still blocks promotion.',
    },
    learning: {
      eyebrow: 'Learning loop',
      title: 'Performance attribution and learning outcomes',
      description:
        'Review outcomes, model performance, and learning-loop movement with clear evidence.',
    },
    proposals: {
      eyebrow: 'Proposal review',
      title: 'Candidate changes and challenger verdicts',
      description:
        'Approve or reject strategy mutations from a table-first queue with explicit expected impact.',
    },
    system: {
      eyebrow: 'Command Center',
      title: 'Decisions, risk, execution, and traceability',
      description: 'A live view of what the system is thinking, doing, and changing right now.',
    },
  },
  panels: {
    executions: 'Executions',
    positions: 'Positions',
    watchlist: 'Watchlist',
    agentDecisions: 'Agent Decisions',
    tradeFeed: 'Trade Feed',
    agentActivity: 'Agent Activity',
    liveActivity: 'Live Activity',
    agentScorecards: 'Agent Scorecards',
    unrealized: 'Unrealized',
  },
  tables: {
    time: 'Time',
    symbol: 'Symbol',
    side: 'Side',
    qty: 'Qty',
    avg: 'Avg',
    last: 'Last',
    mktValue: 'Mkt Value',
    pnl: 'P&L',
    pnlPct: 'P&L%',
    entryExit: 'Entry → Exit',
  },
  empty: {
    activity: 'No activity yet — events stream in here as the pipeline runs.',
    agents: 'No active agents',
    decisions: 'No buy/sell decisions yet',
    agentDecisions: 'No agent decisions yet',
    fills: 'No fills yet',
    positions: 'No open positions',
    closedTrades: 'No closed trades yet this session',
    agentActivity: 'Waiting for agent activity',
    learningOutcomes: 'No fills yet — learning outcomes appear after execution and grading.',
    proposals: 'No strategy proposals yet — evidence appears here after reflection.',
    proposalsReview: 'No proposals awaiting review.',
    learningEvents: 'No learning-agent events have streamed yet.',
  },
  banners: {
    reconnecting: 'Reconnecting to live feed…',
    memoryModeTitle: 'Memory mode',
    memoryModeUnavailable: '— database unavailable',
    memoryModeBody:
      'Data is ephemeral and will be lost on restart. Trade history and grades are stored in-process only.',
    memoryModeDbReason: ': PostgreSQL unreachable',
  },
  cognitive: {
    eyebrow: 'Cognitive engine',
    title: 'Cognitive Trading Brain',
    subtitleLoop: 'Live reasoning · self-evolving config',
    subtitleEvents: 'events on the stream',
    headerChip: 'Reasoning and evolution',
    memoryMode: 'Memory mode',
    memoryModeTitle:
      'Postgres is down — running on Redis + in-memory state. Live decisions and the perception chain are real; grades and closed-trade outcomes are limited until the database is back.',
    apiError: 'Could not reach the cognitive API:',
    apiErrorFallback: 'failed to load cognitive state',
    cmd: {
      decisions: 'Decisions',
      buysShort: 'B',
      sellsShort: 'S',
      holdsShort: 'H',
      llmReasoning: 'LLM Reasoning',
      reasoned: 'model-reasoned',
      fallbacks: 'rule-based',
      llmAllReasoned: 'every decision model-reasoned',
      llmDegraded: 'rule-based fallbacks active',
      llmUnknown: 'reasoning status unavailable',
      latestDecision: 'Latest Decision',
      avgConfidence: 'avg confidence',
      activeConfig: 'Active Config',
      configVersion: 'directive version',
      latestReasoning: 'Latest Reasoning',
      perceptionChain: 'Perception chain · tools this decision used',
      noTools: 'No tools recorded for this decision.',
      noDecisions:
        'No decisions yet — the reasoning agent emits one per market-tick batch once signals flow.',
      ruleBasedTag: 'rule-based',
      ruleBasedTitle: 'LLM unavailable — rule-based fallback, not model reasoning.',
      msSuffix: 'ms',
      pctSuffix: '%',
    },
    tracePerception: 'Perception',
    traceLlm: 'Reasoning',
    traceModelReasoned: 'model-reasoned',
    traceRuleBased: 'rule-based fallback',
    traceNoTools: 'no tools recorded',
    tabs: {
      command: 'Command Center',
      loop: 'Cognition Loop',
      agents: 'Cognitive Agents',
      proposals: 'Proposals',
      evolution: 'Evolution',
      traces: 'Trace Explorer',
      events: 'Event Stream',
    },
    loopStages: [
      { label: 'Reasoning', note: 'LLM + evolving directive' },
      { label: 'Decision', note: 'records tools used' },
      { label: 'Execution', note: 'fills → realized PnL' },
      { label: 'Grade', note: '4-D score + tool alpha' },
      { label: 'Reflection', note: 'LLM hypotheses' },
      { label: 'Proposer', note: 'LLM drafts directive' },
      { label: 'Apply', note: 'prompt store / PR / issue' },
    ],
    loopTitle: 'Self-Evolving Cognition Loop',
    directiveEvolves: 'directive evolves',
    loopDescription:
      'Each cycle the LLM grades tools by realized PnL and drafts a sharper reasoning directive ' +
      '(assembled beneath the immutable constitution). An approved proposal promotes it and the ' +
      'next decision uses it — config changes ship as auto-PRs, code/feature work as issues.',
    system: 'System',
    healthy: 'Healthy',
    warmingUp: 'Warming up',
    tradesGraded: 'trades graded',
    topDecision: 'Top Decision',
    band: 'band',
    activeConfig: 'Active Config',
    merged: 'merged',
    proposed: 'proposed',
    proposalPipeline: 'Proposal Pipeline',
    approved: 'approved',
    rejected: 'rejected',
    backtested: 'backtested',
    agentHealth: 'Agent Health',
    decisionFlow: 'Decision Flow — score = Σ signalᵢ · weightᵢ',
    decisionQuality: 'Decision Quality (counterfactual)',
    bestActionRate: 'best-action rate',
    meanRegret: 'mean regret',
    qualityNote: 'share of closed trades where the chosen action beat the BUY/SELL/HOLD alternatives',
    drift: 'Drift',
    noDrift: 'No drift detected',
    was: 'was',
    events: 'events',
    score: 'score',
    samples: 'n',
    lastPrefix: 'last:',
    proposalsEmpty:
      'No proposals yet — the ProposalAgent fires once an agent shows a statistically backed edge.',
    columns: {
      proposal: 'Proposal',
      change: 'Change',
      backtestDelta: 'Backtest Delta',
      verdict: 'Challenger Verdict',
      status: 'Status',
    },
    deltaPnl: 'ΔPnL',
    deltaSharpe: 'ΔSharpe',
    deltaDrawdown: 'DD',
    verdictApprove: 'APPROVE',
    verdictReject: 'REJECT',
    risk: 'risk',
    pendingReview: 'Pending review',
    configEvolution: 'Config Evolution',
    configEvolutionEmpty:
      'No config versions yet — appears once the learning loop promotes a weight/threshold change.',
    active: 'active',
    directivePromoted: 'directive promoted',
    successByType: 'Proposal Success by Type',
    noProposalsScored: 'No proposals scored yet.',
    noTraces: 'No trades traced yet.',
    steps: {
      signals: 'Agent signals',
      reasoning: 'Reasoning',
      decision: 'Decision',
      riskGate: 'Risk gate',
      execution: 'Execution',
      outcome: 'Outcome',
      counterfactual: 'Counterfactual',
      grade: 'Grade',
    },
    allowed: 'allowed',
    blocked: 'blocked',
    atScore: '@ score',
    best: 'best',
    regret: 'regret',
    choseBest: 'chose best',
    suboptimal: 'suboptimal',
    gradeOverall: 'overall',
    gradeDirection: 'dir',
    gradeRisk: 'risk',
    gradeExecution: 'exec',
    gradeTiming: 'timing',
    eventColumns: {
      seq: '#',
      type: 'type',
      source: 'source',
      trace: 'trace',
    },
  },
  decisions: {
    title: 'Recent Decisions',
    ruleBased: 'rule-based',
    ruleBasedHeaderTitle:
      'LLM unavailable — these are rule-based fallback decisions, not model reasoning.',
    ruleBasedRowTitle: 'LLM unavailable — rule-based fallback, not model reasoning.',
    lastHour: 'last 1h',
    allTime: 'all-time',
    allTimeTitle:
      "All decisions stored (most-recent, capped at 50) — not a last-hour figure, so it won't equal Buys + Sells + Holds",
    buys: 'Buys:',
    sells: 'Sells:',
    holds: 'Holds:',
    total: 'Total:',
    reasoningChain: 'Reasoning chain · tools this decision used',
    toolFallback: 'tool',
  },
  tradingView: {
    fallbackSkipReasoning: 'Rule-based fallback decision',
    fallbackRejectSignal: 'Signal rejected (rule-based)',
    fallbackUseLastReflection: 'Reused last reflection',
    fallbackDefault: 'Rule-based fallback (LLM unavailable)',
    fills: 'fills',
    signals: 'Signals:',
    decisions: 'Decisions:',
    eePrefix: 'EE:',
    closedTrades: 'Closed Trades',
    closed: 'closed',
    units: 'units',
    tracePrefix: 'trace:',
    agentFallback: 'Agent',
    statSessionPnl: 'Session P&L',
    statWinRate: 'Win Rate',
    statTotalFills: 'Total Fills',
    statOpenPositions: 'Open Positions',
    subCompleted: 'completed',
    subPosition: 'position',
    subPositions: 'positions',
    subNoClosedTrades: 'no closed trades',
    subOf: 'of',
    realized: 'realized',
    unrealized: 'unrealized',
  },
  learningLoop: {
    title: 'Learning Loop',
    latestGrade: 'Latest Grade',
    tradingPaused: 'Trading Paused',
    paused: 'PAUSED',
    live: 'LIVE',
    signalWeight: 'Signal Weight',
    dampened: 'dampened',
    full: 'full',
    proposals: 'Proposals',
    appliedPending: 'applied / pending',
    suspendedAgents: 'Suspended Agents',
    recentProposals: 'Recent Proposals',
    noProposals: 'No proposals yet.',
    applied: 'applied',
    pending: 'pending',
    lossAttribution: 'Loss Attribution',
    noClosedTrades: 'No closed trades yet — attribution appears once positions close.',
    challengerShadows: 'Challenger Shadows',
    noChallengers: 'No shadow challengers running.',
    running: 'running',
    beatingBaseline: 'beating baseline',
    promotionProposedSingular: 'promotion proposed',
    promotionProposedPlural: 'promotions proposed',
    followChallengers: 'Follow challengers →',
    paramEvolution: 'Parameter Evolution — Pending PRs',
    noPendingParams:
      'No pending parameter changes. The learning loop opens a PR when it has evidence to tune a parameter.',
    columns: {
      type: 'Type',
      action: 'Action',
      state: 'State',
      when: 'When',
      symbol: 'Symbol',
      signal: 'Signal',
      trades: 'Trades',
      losses: 'Losses',
      totalPnl: 'Total PnL',
      avgPnl: 'Avg PnL',
      parameter: 'Parameter',
      current: 'Current',
      proposed: 'Proposed',
      reason: 'Reason',
    },
  },
  learning: {
    title: 'Learning Control Plane',
    description:
      'Live learning evidence from the dashboard store — graded fills, proposal outcomes, and learning-agent activity.',
    sourceBadge: 'Source: live dashboard state',
    statGradedTrades: 'Graded Trades',
    statWinRate: 'Win Rate',
    statTotalPnl: 'Total PnL',
    statAvgGradeScore: 'Avg Grade Score',
    statProposalQueue: 'Proposal Queue',
    gradedOutcomesTitle: 'Graded Trade Outcomes',
    gradedOutcomesSubtitle: 'Recent fills with grades, P&L, and trace links.',
    latest: 'Latest',
    proposalOutcomesTitle: 'Proposal Outcomes',
    proposalOutcomesSubtitle: 'Strategy changes generated by the learning loop.',
    total: 'total',
    currentStateTitle: 'Current Learning State',
    latestGrade: 'Latest Grade',
    latestProposal: 'Latest Proposal',
    noProposalYet: 'No proposal generated yet',
    activityTitle: 'Learning Agent Activity',
    activitySubtitle: 'Grade, reflection, proposal, and learning events.',
    events: 'events',
    noMessage: 'No message provided.',
    notRated: 'NR',
    units: 'units',
    filled: 'filled',
    graded: 'graded',
    pending: 'pending',
    approved: 'approved',
    columns: {
      trade: 'Trade',
      pnl: 'P&L',
      grade: 'Grade',
      score: 'Score',
      lifecycle: 'Lifecycle',
      trace: 'Trace',
      change: 'Change',
      expected: 'Expected',
      gradeDelta: 'Grade Δ',
      status: 'Status',
    },
  },
  pipeline: {
    title: 'Agent Pipeline',
    stagesLive: 'stages live',
    description:
      'How data moves through the system — each box is an agent, the number is what it has produced.',
    loopNote:
      "Grades and re-weighted factors loop back into Reasoning — that's how the system learns over time.",
    toneLive: 'Live',
    toneIdle: 'Idle',
    toneStale: 'Stale',
    toneError: 'Error',
    toneWaiting: 'Waiting',
  },
  backendOffline: {
    bannerPrefix: 'Backend unreachable — showing last known data',
    dismissAria: 'Dismiss backend offline banner',
    emptyTitle: 'Backend offline — no data received yet',
    emptyBody:
      'The dashboard cannot reach the trading API and nothing has been loaded in this session, ' +
      'so there is no last-known data to show. Panels will populate automatically as soon as ' +
      'the backend is reachable again.',
  },
  llmDegraded: {
    downMessage: 'Reasoning LLM down — running in fallback mode',
    degradedMessage: 'Reasoning LLM degraded — decision quality reduced',
    providerLabel: 'provider:',
    successRateStem: 'LLM success rate',
    successRateWindow: 'over the last window.',
    fallbackEnabled: 'Cloud fallback is enabled.',
    fallbackDisabled:
      'Cloud fallback is disabled — reasoning fails closed (new signals are rejected, no naive trades).',
    cascade:
      ' Knock-on: with reasoning degraded, few/no trades close, so the learning agents' +
      ' (Grade · IC · Reflection · Proposer) sit idle until trading resumes — wiring is intact,' +
      ' the pipeline is waiting on the LLM.',
  },
  llmHealth: {
    title: 'LLM Health',
    unavailable: 'Metrics unavailable',
    statusLive: 'Live',
    statusDegraded: 'Degraded',
    statusDown: 'Down',
    statusUnknown: 'Unknown',
    callSuccess: 'Success',
    callRateLimited: 'Rate limited',
    callRateLimitedAbbr: 'RL',
    callTimeout: 'Timeout',
    callTimeoutAbbr: 'TO',
    callError: 'Error',
    callErrorAbbr: 'ERR',
    localStripTitle: 'Local GPU / LM Studio',
    localActive: 'Active',
    localOffline: 'Offline',
    mismatchTitle: 'Remote backend cannot reach localhost.',
    mismatchHint: 'Use Tailscale, a public tunnel, or run the backend locally.',
    host: 'host:',
    model: 'Model:',
    provider: 'Provider:',
    hostLabel: 'Host:',
    latency: 'Latency:',
    fallbacks: 'Fallbacks:',
    fallback: 'Fallback:',
    disabled: 'disabled',
    errorLabel: 'Error:',
    loaded: 'Loaded:',
    successRate: 'Success Rate:',
    avgLatency: 'Avg Latency:',
    rateLimited: 'Rate Limited:',
    timeouts: 'Timeouts:',
    dailyCalls: 'Daily Calls:',
    lifetime: 'Lifetime:',
    last: 'last',
    noCallsInWindow: 'No calls in window — last:',
    lastError: 'Last error:',
    callDelay: 'Call Delay',
    gradeAdjusted: 'adjusted',
    gradeDefault: 'default',
    gradeAgent: 'GradeAgent',
    lastCalls: 'calls',
    lastCallsPrefix: 'Last',
  },
  toolGovernance: {
    title: 'Tool Governance · Runtime Registry',
    enabled: 'enabled',
    description:
      'The data look-ups the reasoning LLM may consult before a buy/sell call — each is graded by ' +
      'the realized PnL of the trades it influenced, and money-losing (negative-alpha) tools are ' +
      'proposed for automatic disable.',
    legend:
      "On = the AI may use it · Off = switched off. Alpha = profit credited to the tool (a 'prior' " +
      "tag = an early estimate before any trade has scored it). Calls = how many times it's been used.",
    haveRun: 'have run on a live trade so far.',
    suggestionsTitle: 'What the system suggests',
    suggestionsLegend:
      'Disable = losing money, switch it off · Prioritize = the best earner, keep it · Review = ' +
      'not used yet, just watching. Disable suggestions become a proposal on the Proposals page; ' +
      'approve it there and the tool is switched off automatically.',
    noTools: 'No tools registered.',
    noCallsTitle: 'No tool calls yet',
    noCallsBodyPrefix: 'tools are registered and waiting; every alpha is still a seeded prior.',
    noCallsBodySuffix:
      'The full ledger appears once the reasoning LLM starts consulting tools and closed trades ' +
      'let the GradeAgent attribute realized PnL to them.',
    on: 'on',
    off: 'off',
    ok: 'ok',
    unused: 'unused',
    prior: 'prior',
    requires: 'requires:',
    unlocks: '→ unlocks',
    unusedDownstream: 'downstream tool — runs on a live order/risk event, not at reasoning time',
    unusedGatedPrefix: 'gated — eligible only once',
    unusedGatedSuffix: 'is set',
    unusedEligible: 'eligible — the reasoning LLM has not selected it yet',
    columns: {
      tool: 'Tool',
      status: 'Status',
      calls: 'Calls',
      alpha: 'Alpha',
      latency: 'Latency',
      err: 'Err',
    },
  },
  promptEvolution: {
    title: 'Self-Evolving Prompt · Reasoning Directive',
    evolving: 'evolving',
    frozen: 'frozen',
    autoApply: 'auto-apply',
    manual: 'manual',
    description:
      'The learned directive the LLM refines each cycle — assembled beneath the immutable ' +
      'constitution. Reflection drafts it, an approved proposal promotes it, the next decision uses it.',
    emptyIntroPrefix: 'No evolved directive yet — the reasoning agent runs on the',
    emptyIntroConstitution: 'immutable constitution',
    emptyIntroSuffix:
      'alone. A directive is the learned guidance layered beneath it, and only appears after the learning loop closes a full cycle:',
    step1: 'closed trades are graded',
    step2: 'Reflection drafts an improved directive',
    step3: 'it ships as a PROMPT_EVOLUTION proposal — review it on the Proposals page',
    step4Approval: 'approval',
    step4Stem: 'it becomes the active directive, shown here with its version & full history',
    step4Prefix: 'on',
    warmingUp: 'Evolution is on — nothing proposed yet (the loop is still warming up).',
    frozenHint: 'Evolution is frozen — enable PROMPT_EVOLUTION to let the directive learn.',
    active: 'Active',
    why: 'why:',
    historyPrefix: 'History ·',
    priorVersion: 'prior version',
    priorVersions: 'prior versions',
    noRationale: 'no rationale recorded',
  },
  liveReasoning: {
    title: 'Live Reasoning',
    description:
      "Exactly what the buy/sell AI is running now: the fixed rulebook + the tools it's " +
      'allowed to use + the answer format. Challengers shadow it; proposals would change it.',
    llmLive: 'live',
    llmDegraded: 'LLM degraded',
    llmDown: 'LLM down · fallback',
    llmUnknown: 'awaiting LLM',
    degradedBannerDown: 'unavailable',
    degradedBannerDegraded: 'degraded',
    liveBadge: 'live',
    viewPrompt: 'View live prompt',
    hidePrompt: 'Hide prompt',
    toolsHeading: 'Tools the AI may use',
    noTools: 'No tools eligible for this node.',
    challengersHeading: 'Challengers being tested',
    challengersEmpty:
      'No challenger strategy under test — the live strategy runs uncontested until the ' +
      'learning loop spawns a rival to shadow it.',
    proposalsHeading: 'Proposed changes',
    proposalsEmpty: 'No proposals yet — they arrive from the ReflectionAgent.',
    differsBy: 'differs by',
    differsByTitle: 'What this challenger changes versus the live strategy',
    shadowFills: 'shadow fills observed',
    shadowFillsTitle:
      'Simulated fills observed so far out of the test window — the challenger trades in shadow, never with real orders',
    promptVariant: 'prompt variant:',
    toolSet: 'tool set:',
    sameAsLive: 'Same prompt + tools as the live strategy.',
    applied: 'applied',
    confidence: 'confidence',
  },
  challengers: {
    title: 'Challenger Shadows',
    running: 'running',
    description:
      'Rival strategies shadow-trading the live price stream — they never place real orders. ' +
      'Promotion requires the full bar: enough shadow trades, a minimum win rate, positive PnL, ' +
      'positive Sharpe, and beating the baseline on the same ticks. When one clears it, a ' +
      'promotion proposal lands on the Proposals page.',
    emptyState:
      'No shadow challengers running. They spawn from approved challenger promotions or ' +
      'new-agent proposals on the Proposals page.',
    statusPromoted:
      'Promotion fired — cleared every bar (trades, win rate, +PnL, +Sharpe, beats baseline).',
    statusEligible: 'Eligible — promotion proposal fires on the next confirming tick.',
    statusBuilding: 'Building its record — every unmet requirement is listed below.',
    statusWarming: 'Warming up — no shadow round-trips closed yet.',
    badgePromoted: 'promotion proposed',
    badgeEligible: 'eligible',
    badgeWarming: 'warming up',
    dotLive: 'live — ticking',
    dotStale: 'stale — no recent tick',
    statTrades: 'Shadow trades',
    statWinRate: 'Win rate',
    statPnl: 'Shadow PnL',
    statSharpe: 'Sharpe',
    progressLabel: 'shadow trades toward eligibility',
    recentTrades: 'recent shadow trades',
    never: 'never',
  },
  agentsPage: {
    kpiAgentsOnline: 'Agents Online',
    kpiAgentsOnlineNote: 'in pipeline · live = heartbeat < 2m',
    kpiMarketData: 'Market Data',
    streaming: 'streaming',
    idle: 'idle',
    kpiDecisionsHour: 'Decisions · 1h',
    kpiNotificationsHour: 'Notifications · 1h',
    storedNote: 'stored (max 20)',
    noDecisionData: 'No decision data yet',
    groupLiveActivity: 'Live Activity',
    groupReasoning: 'Reasoning',
    groupIntelligence: 'Intelligence',
    groupLearningLoop: 'Learning Loop',
    groupAgents: 'Agents',
    groupActivity: 'Activity',
    groupDiagnostics: 'Diagnostics',
    diagnosticsTitle: 'System Diagnostics',
    diagnosticsSubtitle: 'Data-wiring health — where these numbers come from. For debugging.',
    dbMemory: 'DB: In-Memory Fallback',
    dbConnected: 'DB: Connected',
    noRecentTimestamp: 'No recent timestamp',
    recentEvents: 'recent events',
    timelineDescription:
      'What the pipeline is doing right now — every signal, decision, execution and alert in the order it happened.',
    promoted: 'promoted',
    promotedTitle:
      'Trust-tier promotion of pipeline agents (sustained A grades). NOT challenger strategy promotion — that arrives as a challenger_promotion proposal on the Proposals page.',
    applying: 'Applying…',
    applyTitle:
      'Give top-graded agents more say, and underperformers less. Safe and optional — nothing trades differently unless trust-weighting is turned on.',
    applyFailed: 'Apply failed',
    unrated: 'unrated',
    noTelemetry: 'No agent telemetry yet.',
    scorecardsDescription:
      "A report card per agent, scored on the work it actually did (completed runs, throughput, " +
      "speed). An agent that hasn't done measurable work yet shows unrated — no grade until it " +
      'earns one. Click a card for the full breakdown. Apply promotions rewards sustained A ' +
      'agents (★ Promoted) with more influence and trims weak ones — optional, and safe to ' +
      'click. This is trust-tier promotion of pipeline agents — separate from challenger ' +
      'strategy promotion, which arrives as a voteable proposal on the Proposals page once a ' +
      'shadow challenger beats the live baseline.',
    wiringHeartbeats: 'Heartbeats (in-memory/Redis):',
    wiringLifecycle: 'Lifecycle rows (DB):',
    wiringLogs: 'Agent logs (DB/WS):',
  },
  agentDetail: {
    loadError: 'Failed to load agent detail',
    noTelemetry: 'no data',
    noTelemetryTitle: 'no telemetry for this dimension yet',
    score: 'score',
    events: 'events',
    runsOk: 'runs ok',
    gradeStreak: 'A/A+ streak:',
    trust: 'trust',
    gradeBreakdown: 'Grade Breakdown',
    learnings: 'Learnings',
    heartbeat: 'Heartbeat',
    recentActivity: 'Recent Activity',
    noRecentRuns: 'No recent runs recorded.',
    dataSource: 'data source:',
    sourceMemory: 'in-memory (DB down)',
    sourceDatabase: 'database',
  },
  proposalQueue: {
    title: 'Proposal Queue',
    subtitle:
      'Table-first review of candidate strategy changes, expected impact, and challenger verdicts.',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    columns: {
      change: 'Candidate Change',
      type: 'Type',
      onApprove: 'On Approve',
      expected: 'Expected Improvement',
      backtestDelta: 'Backtest Delta',
      traceability: 'Traceability',
      status: 'Status',
      decision: 'Decision',
    },
    detailsLink: 'details',
    detailsTitle:
      'View the full proposal — change, what happens on approve, evidence, traceability',
    applied: 'applied',
    appliedByPrefix: 'Applied by the ProposalApplier',
    reviewed: 'Reviewed',
    emptyTitle: 'No proposals awaiting review.',
    emptyIntro:
      'An empty queue is normal — proposals only come from three places, each with real thresholds:',
    emptySources: [
      {
        term: 'Challenger shadows',
        body:
          '— a rival strategy must close ≥25 shadow trades AND beat the live baseline; its ' +
          'challenger_promotion then applies automatically (directive bias + follow-up shadow — ' +
          'no live orders) and the applied record lands here. Progress is on the Learning page; ' +
          'set CHALLENGER_PROMOTION_AUTO_APPLY=false to gate on your approval.',
      },
      {
        term: 'Reflection → Strategy Proposer',
        body:
          '— hypotheses from graded trades with confidence ≥ 0.7, deduped and capped per day. ' +
          'No closed trades → no reflections → nothing here.',
      },
      {
        term: 'Grades C / D / F',
        body:
          '— auto-applied control actions (weight cut, suspension, retirement). These act ' +
          'immediately and are logged, so they never queue here. Good grades (A/B) intentionally ' +
          'create no proposals.',
      },
    ],
  },
  proposalDetail: {
    title: 'Proposal',
    id: 'ID',
    candidateChange: 'Candidate change',
    onApprove: 'On approve',
    routesTo: 'routes to:',
    evidence: 'Evidence',
    confidence: 'confidence',
    backtestDelta: 'backtest delta',
    requiresApproval: 'requires approval',
    yes: 'yes',
    no: 'no',
    traceability: 'Traceability',
  },
  trace: {
    title: 'Trace:',
    agentRuns: 'Agent Runs',
    agentLogs: 'Agent Logs',
    grades: 'Grades',
    emptyTrace:
      "No pipeline trace was recorded for this event. System notifications and rule-based fallback decisions don't flow through the agent pipeline, and in memory mode (no database) trace history clears on restart — only live, in-session traces are available here.",
    loadError: 'Could not load this trace — the dashboard API did not respond.',
    loading: 'Loading…',
  },
} as const
